### ISSUE TITLE
File not found: '..\Version.res'

### ISSUE THREAD

**Issue by TextEditorPro** [ahausladen/DFMCheck#2]
There is Version.rc thou, so easy to fix but just FYI.

Also some "WideChar reduced to byte char in set expression" warnings... can't remember in which version this CharInSet came.

**Comment by ahausladen** [comment]
All existing project files (*.dproj) have the "WideChar reduced" warning disabled. So I guess you created a new one for Delphi 10.4.x. The warning is not necessary for the code as it only uses ASCII characters in the "set of (Ansi)Char" and the compiler generates the correct code. It only causes a problem if you put non-ASCII chars in the Ansi-Char set.
And I don't want to even start talking about the performance of CharInSet.
